Repository MarcosASampaio/services-frontend, pull requests merged in 2022-07, with the labels that each got.

#2 Confirmacao de logout
  angular.json
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/app/auth/services/auth.service.spec.ts
  src/app/auth/services/auth.service.ts
  src/app/funcionarios/components/confirmar-logout/confirmar-logout.component.css
  src/app/funcionarios/components/confirmar-logout/confirmar-logout.component.html
  src/app/funcionarios/components/confirmar-logout/confirmar-logout.component.ts
  src/app/funcionarios/funcionarios.module.ts
  src/app/funcionarios/pages/funcionario/funcionario.component.spec.ts
  src/app/guards/verificacao-token.guard.spec.ts
  src/environments/environment.ts
  src/styles.css
Labels: enhancement

#4 Recaptcha login adicao
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/pages/login/login.component.css
  src/app/auth/pages/login/login.component.html
  src/app/auth/pages/login/login.component.spec.ts
  src/app/auth/pages/login/login.component.ts
  src/app/auth/services/auth.service.ts
  src/app/funcionarios/funcionarios.module.ts
  src/environments/environment.ts
  src/styles.css
Labels: enhancement

#7 Adição dos title
  src/app/app.module.ts
  src/app/auth/pages/login/login.component.ts
  src/app/funcionarios/components/form-funcionario/form-funcionario.component.ts
  src/app/funcionarios/funcionarios.module.ts
  src/app/funcionarios/pages/funcionario/funcionario.component.ts
  src/app/funcionarios/pages/listar-funcionarios/listar-funcionarios.component.spec.ts
  src/app/funcionarios/pages/listar-funcionarios/listar-funcionarios.component.ts
Labels: enhancement

#10 id de cargo no model funcionario
  src/app/funcionarios/models/funcionario.ts
  src/app/funcionarios/pages/funcionario/funcionario.component.ts
Labels: enhancement

#14 campoFormCargo
  src/app/cargos/service/cargo-service.service.ts
  src/app/funcionarios/components/form-funcionario/form-funcionario.component.html
  src/app/funcionarios/components/form-funcionario/form-funcionario.component.ts
  src/app/funcionarios/models/cargo.ts
  src/app/interceptor/interceptor.interceptor.ts
Labels: enhancement

#16 Email pelo Token
  .vscode/settings.json
  angular.json
  src/app/auth/services/auth.service.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
Labels: enhancement

#17 Meta tags
  src/index.html
Labels: enhancement

#20 Adição de tooltips nos botões da aplicação
  src/app/auth/pages/login/login.component.html
  src/app/auth/pages/login/login.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/funcionarios/components/confirmar-delecao/confirmar-delecao.component.html
  src/app/funcionarios/components/confirmar-logout/confirmar-logout.component.html
  src/app/funcionarios/components/confirmar-saida/confirmar-saida.component.html
  src/app/funcionarios/components/form-funcionario/form-funcionario.component.html
  src/app/funcionarios/pages/funcionario/funcionario.component.html
  src/app/funcionarios/pages/listar-funcionarios/listar-funcionarios.component.html
Labels: enhancement

#22 crudCargosFeito
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/pages/login/login.component.html
  src/app/auth/pages/login/login.component.ts
  src/app/auth/services/auth.service.ts
  src/app/cargos/cargo-routing.module.ts
  src/app/cargos/cargo.module.ts
  src/app/cargos/components/cadastrar-cargo/cadastrar-cargo.component.css
  src/app/cargos/components/cadastrar-cargo/cadastrar-cargo.component.html
  src/app/cargos/components/cadastrar-cargo/cadastrar-cargo.component.ts
  src/app/cargos/components/delete-cargo/delete-cargo.component.css
  src/app/cargos/components/delete-cargo/delete-cargo.component.html
  src/app/cargos/components/delete-cargo/delete-cargo.component.ts
  src/app/cargos/pages/cargos/cargos.component.css
  src/app/cargos/pages/cargos/cargos.component.html
  src/app/cargos/pages/cargos/cargos.component.ts
  src/app/cargos/pages/editar-cargo/editar-cargo.component.css
  src/app/cargos/pages/editar-cargo/editar-cargo.component.html
  src/app/cargos/pages/editar-cargo/editar-cargo.component.ts
  src/app/cargos/service/cargo-service.service.ts
  src/app/compartilhar-componentes/compartilhar-componentes.module.ts
  src/app/compartilhar-componentes/navbar/navbar.component.css
  src/app/compartilhar-componentes/navbar/navbar.component.html
  src/app/compartilhar-componentes/navbar/navbar.component.ts
  src/app/funcionarios/components/confirmar-delecao/confirmar-delecao.component.html
  src/app/funcionarios/components/confirmar-logout/confirmar-logout.component.html
  src/app/funcionarios/components/confirmar-saida/confirmar-saida.component.html
  src/app/funcionarios/components/form-funcionario/form-funcionario.component.html
  src/app/funcionarios/components/form-funcionario/form-funcionario.component.ts
  src/app/funcionarios/funcionarios.module.ts
  src/app/funcionarios/models/funcionario.ts
  src/app/funcionarios/pages/funcionario/funcionario.component.css
  src/app/funcionarios/pages/funcionario/funcionario.component.html
  src/app/funcionarios/pages/funcionario/funcionario.component.ts
  src/app/funcionarios/pages/listar-funcionarios/listar-funcionarios.component.html
  src/app/funcionarios/pages/listar-funcionarios/listar-funcionarios.component.ts
  src/app/funcionarios/services/funcionario.service.ts
  src/index.html
Labels: bug, enhancement

#26 correcaoBugs
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/index.html
Labels: bug

#30 crudClientes
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/cargos/pages/cargos/cargos.component.html
  src/app/clientes/cliente/cliente-routing.module.ts
  src/app/clientes/cliente/cliente.module.ts
  src/app/clientes/componentes/deletar-cliente/deletar-cliente.component.css
  src/app/clientes/componentes/deletar-cliente/deletar-cliente.component.html
  src/app/clientes/componentes/deletar-cliente/deletar-cliente.component.ts
  src/app/clientes/componentes/editar-cliente/editar-cliente.component.css
  src/app/clientes/componentes/editar-cliente/editar-cliente.component.html
  src/app/clientes/componentes/editar-cliente/editar-cliente.component.ts
  src/app/clientes/componentes/form-cliente/form-cliente.component.css
  src/app/clientes/componentes/form-cliente/form-cliente.component.html
  src/app/clientes/componentes/form-cliente/form-cliente.component.ts
  src/app/clientes/pages/cliente/cliente.component.css
  src/app/clientes/pages/cliente/cliente.component.html
  src/app/clientes/pages/cliente/cliente.component.ts
  src/app/clientes/service/cliente.service.spec.ts
  src/app/clientes/service/cliente.service.ts
  src/app/compartilhar-componentes/navbar/navbar.component.html
  src/app/funcionarios/models/cliente.ts
  src/app/funcionarios/models/endereco.ts
Labels: enhancement
